export const CATEGORIES = ['Shirt', 'T-Shirt', 'Pants', 'Saree', 'Chudithar', 'Kids Wear', 'Inner Wear', 'Accessories'];

export const PREDEFINED_COLORS = [
  { name: 'Red', hex: '#FF0000' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'Green', hex: '#008000' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Black', hex: '#000000' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Orange', hex: '#FFA500' },
  { name: 'Grey', hex: '#808080' },
];

export const SHIRT_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', 'General'];

export const TRANSLATIONS = {
  en: {
    appName: 'Viyabaari',
    dashboard: 'Dashboard',
    stock: 'Stock',
    accounts: 'Accounts',
    profile: 'Profile',
    addStock: 'Add Stock',
    itemName: 'Item Name',
    price: 'Price',
    category: 'Category',
    quantity: 'Quantity',
    save: 'Save',
    update: 'Update',
    delete: 'Delete',
    edit: 'Edit',
    photo: 'Add Photo',
    color: 'Color',
    size: 'Size',
    addTransaction: 'Add Transaction',
    editTransaction: 'Edit Transaction',
    income: 'Income',
    expense: 'Expense',
    partyName: 'Party Name',
    description: 'Description',
    resetLinkSent: 'Password reset link sent to your email.',
    totalStockValue: 'Total Stock Value',
    totalItems: 'Total Items',
    lowStock: 'Low Stock Items',
    recentTransactions: 'Recent Transactions',
    netBalance: 'Net Balance',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    logout: 'Logout',
    setupServer: 'Setup Cloud Database',
    sync: 'Sync Data',
    language: 'Language',
    clearData: 'Clear All Data',
    settings: 'Settings',
  },
  ta: {
    appName: 'வியாபாரி',
    dashboard: 'முகப்பு',
    stock: 'சரக்கு',
    accounts: 'கணக்கு',
    profile: 'விவரம்',
    addStock: 'சரக்கு சேர்',
    itemName: 'பொருள் பெயர்',
    price: 'விலை',
    category: 'வகை',
    quantity: 'அளவு',
    save: 'சேமி',
    update: 'புதுப்பி',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    photo: 'படம் சேர்',
    color: 'நிறம்',
    size: 'அளவு',
    addTransaction: 'கணக்கு சேர்',
    editTransaction: 'கணக்கு திருத்து',
    income: 'வரவு',
    expense: 'செலவு',
    partyName: 'நபர் பெயர்',
    description: 'விளக்கம்',
    resetLinkSent: 'கடவுச்சொல் மாற்றும் இணைப்பு அனுப்பப்பட்டது.',
    totalStockValue: 'மொத்த சரக்கு மதிப்பு',
    totalItems: 'மொத்த பொருட்கள்',
    lowStock: 'குறைந்த இருப்பு',
    recentTransactions: 'சமீபத்திய வரவு செலவு',
    netBalance: 'மொத்த இருப்பு',
    totalIncome: 'மொத்த வரவு',
    totalExpense: 'மொத்த செலவு',
    logout: 'வெளியேறு',
    setupServer: 'கிளவுட் டேட்டாபேஸ் அமை',
    sync: 'தரவை ஒத்திசை',
    language: 'மொழி',
    clearData: 'எல்லா தரவையும் அழி',
    settings: 'அமைப்புகள்',
  }
};
